name: Test macOS Runner

on:
  workflow_dispatch:

jobs:
  macos-test:
    runs-on: [self-hosted, macos]

    steps:
      - name: Print runner info
        run: |
          echo "Running on:"
          uname -a
          sw_vers

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test with conda
        shell: bash
        run: |
          echo "Running test..."
          ls
          pwd
          conda env list

          git clone https://github.com/DrewThomasson/ebook2audiobook.git

          cd ebook2audiobook

          # Properly initialize Conda
          # source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh

      - name: Run ebook2audiobook help test
        shell: bash
        run: |
          echo "Running test..."
          cd ebook2audiobook
          ./ebook2audiobook.sh --help

      - name: Run ebook2audiobook quick test
        shell: bash
        run: |
          echo "Running test..."
          cd ebook2audiobook
          ./ebook2audiobook.sh --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine yourtts
