name: Test macOS Runner

on:
  workflow_dispatch:

jobs:
  macos-E2A-Install:
    runs-on: [self-hosted, macos]

    steps:
      - name: Print runner info
        run: |
          echo "Running on:"
          uname -a
          sw_vers

      - name: Checkout this (generated_documentation) repository
        uses: actions/checkout@v4

      - name: Clone ebook2audiobook to short path
        run: |
          # rm -rf /tmp/ebook2audiobook
          # git clone https://github.com/DrewThomasson/ebook2audiobook.git /tmp/ebook2audiobook
          cd /tmp/ebook2audiobook
          grep -qx 'set -e' ebook2audiobook.sh || sed -i '' '1s;^;set -e\n;' ebook2audiobook.sh

      - name: Initalize conda for Unidict
        shell: bash
        working-directory: /tmp/ebook2audiobook
        run: |
          echo "Initializing conda..."
          # Properly initialize Conda, if needed (Needed for unidict to download) you may need a diff for mac and windows and mac depending on the runner
          source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh
          echo "conda initilized!"

      - name: Ebook2audiobook install
        shell: bash
        working-directory: /tmp/ebook2audiobook
        run: |
          echo "Running help install test..."
          export TMPDIR=/tmp
          # ./ebook2audiobook.sh --help
          ./ebook2audiobook.sh --headless --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine yourtts

      - name: Fail sh
        shell: bash
        working-directory: /tmp/ebook2audiobook
        run: |
          echo "Running Fail Test..."
          export TMPDIR=/tmp
          ./ebook2audiobook.sh --headless --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine NotRealTTS

