name: Test macOS Runner

on:
  workflow_dispatch:

jobs:
  macos-test:
    runs-on: [self-hosted, macos]

    steps:
      - name: Print runner info
        run: |
          echo "Running on:"
          uname -a
          sw_vers

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test with conda
        shell: bash
        run: |
          echo "Running test..."
          ls
          pwd
          conda env list

          # Properly initialize Conda
          source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh
          conda activate base

          python -c "print('poop')"

      - name: Run ebook2audiobook help test
        shell: bash
        run: |
          echo "Running test..."
          ./ebook2audiobook.sh --help

      - name: Run ebook2audiobook quick test
        shell: bash
        run: |
          echo "Running test..."
          ./ebook2audiobook.sh --headless --script_mode full_docker --language eng --ebooks_dir "tools/workflow-testing" --tts_engine FAIRSEQ
