name: Test macOS Runner

on:
  workflow_dispatch:

jobs:
  macos-test:
    runs-on: [self-hosted, macos]

    steps:
      - name: Print runner info
        run: |
          echo "Running on:"
          uname -a
          sw_vers

      - name: Checkout this (generated_documentation) repository
        uses: actions/checkout@v4

      - name: Clone ebook2audiobook to short path
        run: |
          rm -rf /tmp/ebook2audiobook
          git clone https://github.com/DrewThomasson/ebook2audiobook.git /tmp/ebook2audiobook

      - name: Run test with conda
        shell: bash
        working-directory: /tmp/ebook2audiobook
        run: |
          echo "Running test..."
          ls
          pwd
          conda env list

          # Properly initialize Conda, if needed
          source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh

      - name: Run ebook2audiobook help test
        shell: bash
        working-directory: /tmp/ebook2audiobook
        run: |
          echo "Running test..."
          export TMPDIR=/tmp
          ./ebook2audiobook.sh --help
          # conda activate ./python_env/
          # python -m unidic download
          # conda deactivate

      - name: Run ebook2audiobook quick test
        shell: bash
        working-directory: /tmp/ebook2audiobook
        run: |
          echo "Running test..."
          ./ebook2audiobook.sh --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine yourtts
