# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Main workflow is running"
