name: Translate README

on:
  workflow_dispatch:
  push:
    paths:
      - README.md

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Translate README
        run: |
          import os
          import requests
          import json

          # Languages to translate into: fr = French, es = Spanish, de = German, zh = Chinese, etc.
          target_languages = ["fr", "es", "de", "zh"]

          # Read the original README.md
          with open("README.md", "r", encoding="utf-8") as f:
              readme_content = f.read()

          os.makedirs("readme", exist_ok=True)

          for lang in target_languages:
              print(f"Translating to {lang}...")
              resp = requests.post(
                  "https://libretranslate.de/translate",
                  headers={"Content-Type": "application/json"},
                  data=json.dumps({
                      "q": readme_content,
                      "source": "en",
                      "target": lang,
                      "format": "text"
                  })
              )
              if resp.status_code == 200:
                  translated = resp.json()["translatedText"]
                  with open(f"readme/README.{lang}.md", "w", encoding="utf-8") as out:
                      out.write(translated)
              else:
                  print(f"Failed to translate to {lang}: {resp.text}")

        shell: python

      - name: Commit and create PR with translated READMEs
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add translated READMEs"
          title: "Add translated README files"
          body: "This PR adds translated versions of README.md to the /readme directory."
          branch: "translated-readmes"
          add-paths: |
            readme/README.*.md
